config/routes.rb
LatihanBlog::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :authentications, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :post_categories

  get "comment/index"

  get "comment/create"

  get "search" => "frontpage#search"

  mount Ckeditor::Engine => '/ckeditor'

  get "frontpage/index"

  get "about_me" => 'frontpage#about_me', :as => :about_me
  get "contact_me" => 'frontpage#contact_me', :as => :contact_me
  post "send_contact" => "frontpage#send_contact", :as => :send_contact
  get "portfolios" => "frontpage#portfolios", :as => :portfolios
  get "frontpage/:id/detail_post" => "frontpage#detail_post", :as => :detail_post
  post "frontpage/add_new_comment" => "frontpage#add_new_comment"
  get "frontpage/:id/category_post" => "frontpage#category_post", :as => :category_post

  resources :posts do
    resources :comments
  end

  match 'tagged' => 'posts#tagged', :as => 'tagged'
  match 'tagged_front' => 'frontpage#tagged', :as => 'taggedfront'

  root :to => 'frontpage#index'

end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController


  def index
    @posts = Post.display_frontpage(params[:page])
  end

  def about_me
    @page_title = "About me"
    @time = Time.now
  end

  def contact_me
    @page_title = "Contact me"
    @contacts = Contact.new
    @send_contact = send_contact_url
  end

  def portfolios
    @page_title = "My portfolios"
  end

  def detail_post
    @post = Post.joins(:post_category).find(params[:id])
    @comments = @post.comments.all
    @comment = @post.comments.new
  end

  def send_contact
    @contacts = Contact.new(params[:contacts])

    if @contacts.save
      redirect_to contact_me_url, notice: 'News was successfully created.'
    else
      render action: "contact_me"
    end
  end

  def search
    @word = params[:word]
    @posts = Post.where("description like ?", "%#{@word}%")
    

    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @posts }
    end
  end

  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.postall
    end
  end

  def category_post
    @posts = Post.display_category(params[:page], params[:id])
    respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @posts }
    end
  end


end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/views/frontpage/_comment.html.erb
  <dt><%= comment.title   %></dt>
  <dd><%= comment.comment  %></dd>
  <hr>

app/views/frontpage/about_me.html.erb
<p>Hi, my name is Mada Aryakusumah. I'am programmer in 41studio.</p>
<address>
  <strong>Mada Aryakusumah</strong><br />
  Tar road no 1, Batujajar <br />
  Bandung, West Java <br />
  <abbr title="Phone">P: <%= number_to_phone(212109909034) %>
</abbr>

</address>
<p>Time saat ini <%= @time %> </p>

app/views/frontpage/contact_me.html.erb
<div class="span3 offset2 thumbnail">
  <div style="padding: 10px 10px 10px 10px">
  <% if notice  %>
    <div class="alert fade in">
      <p><%= notice %></p>
    </div>
  <% end   %>


  <%= form_for @contacts, :url => send_contact_path, :html => { :class => 'form-vertical' } do |f| %>
  <% if @contacts.errors.any?   %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <ul>
        <% @contacts.errors.full_messages.each do |msg|  %>
          <li><%= msg %></li>
        <% end   %>
      </ul>
    </div>
  <% end %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :size => 50, :placeholder => 'Your name..', :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.email_field :email, :placeholder => 'you@gmail.com', :class => 'email_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :message, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :message, :class => 'text_area', :placeholder => 'Your message', :size=> "31x10" %>
      </div>
    </div>


    <%= f.submit 'send', :class => 'btn btn-primary' %>
    <%= f.submit "reset", :type => "reset", :class => 'btn'  %>
  <% end %>
  </div>
</div>

app/views/frontpage/detail_post.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    $("#komen").click(function(){
      $("#form_komen").fadeIn();
    });

  });
</script>

<p>
<h1><b><%= @post.title %></b></h1>
<small><em>Category</em> <span class="label"><%= @post.post_category.name  %></span></small>
</p>

<p>
  <%= if @post.picture.blank?
    puts 'tes'
  else image_tag @post.picture.url.to_s
  end %>
</p>

<p>
  <%= @post.description.html_safe %>
</p>
<% @post.tags.any? %>
<small>Tag</small>
<% @post.tags.each do |tag| %>
  <%= link_to taggedfront_url(:tag => tag.name) do %>
    <span class="label label-info"><i class="icon-tag"></i> <%= tag.name %></span>
  <% end  %>
<% end %>

<br />
<br />
<a href="#" id="komen">Comment this post</a>


<div id="form_komen" style="display : none">
  <%= form_for [@post, @comment], :remote => true do |f| %>

    <% unless user_signed_in? %>
      <div class="control-group">
        <%= f.label :name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :title, :class => 'text_field' -%>
        </div>
      </div>
    <% end   %>

    <div class="control-group">
      <%= f.label :comment, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area(:comment, rows: 3, cols: 40) %>
      </div>
    </div>

    <div class="validation-error"></div>
    <%= f.submit %>
  <% end %>
  <br />
</div>

<div id="sukses" style="display: none">
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= 'thanks for comment' %>
  </div>
</div>


<div id="comments">
  <dl>
    <%= render partial: 'comment', collection: @comments  %>
  </dl>
</div>

app/views/frontpage/index.html.erb
<div class="span8">
  <div class="hero-unit">
    <h1>Hello, world!</h1>
    <p>Welcome to my blog. You can many thing about ruby on rails in here</p>
  </div>
</div>
<div class="span8">
  <% @posts.each do |post| %>
    <h2><%= post.title   %></h2>

    <div class="row">
      <div class="span3"><small><em>Category</em> <span class="label"><%= post.post_category.name  %></span></small></div>
      <div class="span3 pull-right"><small><em>Posted by </em> <%= post.user.name %></small></div>
    </div>
    <p><%= if controller.action_name == 'search'
        highlight(post.description.html_safe,@word)
      else
        sanitize truncate(strip_tags(post.description), length:300)
      end
    %></p>
    <p><%= link_to "Detail »", detail_post_path(post), :class => "btn"   %></p>
    <hr />
  <% end %>
  <%= paginate @posts if controller.action_name == 'index' %>
</div>

app/views/frontpage/portfolios.html.erb
<p>My portfolios</p>

<% content_for :sidebar do %>
  <blockquote>
    <p>More code, more pain</p>
    <small>Mada <cite title="Source Title">Arya</cite></small>
  </blockquote>
<% end  %>


<div class="row-fluid">
            <ul class="thumbnails">
              <li class="span4">
                <div class="thumbnail">
                  <a class="thumbnail" href="#"><img src="http://madaarya.com/images/pgp.png" alt="" /></a>
                  <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a href="#" class="btn btn-primary">Action</a> <a href="#" class="btn">Action</a></p>
                  </div>
                </div>
              </li>
              <li class="span4">
                <div class="thumbnail">
                  <a class="thumbnail" href="#"><img src="http://madaarya.com/images/hmmi.png" alt="" /></a>
                  <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a href="#" class="btn btn-primary">Action</a> <a href="#" class="btn">Action</a></p>
                  </div>
                </div>
              </li>
              <li class="span4">
                <div class="thumbnail">
                  <a class="thumbnail" href="#"><img src="http://madaarya.com/images/kpu.jpg" alt="" /></a>
                  <div class="caption">
                    <h3>Thumbnail label</h3>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a href="#" class="btn btn-primary">Action</a> <a href="#" class="btn">Action</a></p>
                  </div>
                </div>
              </li>
            </ul>
          </div>

app/views/frontpage/tagged.html.erb
<div class="span8">
  <% @posts.each do |post| %>
    <h2><%= post.title   %></h2>
    <p><%=
      post.description.html_safe
    %></p>
    <% post.tags.any? %>
    <% post.tags.each do |tag| %>
      <%= link_to taggedfront_url(:tag => tag.name) do %>
        <span class="label label-info"><i class="icon-tag"></i> <%= tag.name %></span>
      <% end  %>
    <% end %>
    <p><%= link_to "Detail »", detail_post_path(post), :class => "btn"   %></p>
    <hr />
  <% end %>
  <%= paginate @posts if controller.action_name == 'index' %>
</div>