config/routes.rb
LatihanBlog::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :authentications, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :post_categories

  get "comment/index"

  get "comment/create"

  get "search" => "frontpage#search"

  mount Ckeditor::Engine => '/ckeditor'

  get "frontpage/index"

  get "about_me" => 'frontpage#about_me', :as => :about_me
  get "contact_me" => 'frontpage#contact_me', :as => :contact_me
  post "send_contact" => "frontpage#send_contact", :as => :send_contact
  get "portfolios" => "frontpage#portfolios", :as => :portfolios
  get "frontpage/:id/detail_post" => "frontpage#detail_post", :as => :detail_post
  post "frontpage/add_new_comment" => "frontpage#add_new_comment"
  get "frontpage/:id/category_post" => "frontpage#category_post", :as => :category_post

  resources :posts do
    resources :comments
  end

  match 'tagged' => 'posts#tagged', :as => 'tagged'
  match 'tagged_front' => 'frontpage#tagged', :as => 'taggedfront'

  root :to => 'frontpage#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commentable
  acts_as_taggable
  acts_as_taggable_on :tags
  
  attr_accessible :description, :picture, :title, :post_category_id, :tag_list, :state

  validates :description, :title, :post_category_id, presence: true
  mount_uploader :picture, PictureUploader

  belongs_to :user
  belongs_to :post_category

  def self.display_frontpage(page)
    Post.joins(:post_category, :user).where("state = ?", true).page(page).order('created_at desc').per(5)
  end

  def self.display_category(page, category_id)
    Post.joins(:post_category).where("state = ? AND post_category_id = ?", true, category_id).page(page).order('created_at desc').per(5)
  end

  def self.display_mypost(page, id)
    Post.joins(:post_category).where("user_id = ?", id).page(page).order('created_at desc').per(10)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
 
  def index
    @posts = Post.display_mypost(params[:page], current_user.id)
  end


  def show
    @post = Post.find(params[:id])
  end


  def new
    @post = Post.new
  end


  def edit
    @post = Post.find(params[:id])
  end


  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end


  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      
      else
        format.html { render action: "edit" }
      end
    end
  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else 
      @posts = Post.postall
    end
  end


end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/posts/_form.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    var tags = [];
<% ["php", "ruby", "delphi"].each do |ava_tag| %>
      tags.push("<%= ava_tag %>");
<% end %>
    $("#myTags").tagit({
      availableTags: tags
    });
  });
</script>
<%= javascript_include_tag "ckeditor/init" %>
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @post.errors.any?   %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <ul>
        <% @post.errors.full_messages.each do |msg|  %>
          <li><%= msg %></li>
        <% end   %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%=  select("post", "post_category_id", PostCategory.all.collect {|p| [ p.name, p.id ] }, { :include_blank => true }) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= cktext_area_tag("post[description]", @post.description, :input_html => {:cols => 13, :rows => 20}, :toolbar => 'Easy') %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :picture, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :picture, :class => 'file_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list, :class => 'tagit ui-widget ui-widget-content ui-corner-all', :id=> 'myTags' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <label class="radio">
        <%= radio_button("post", "state", TRUE, :checked => true) %>
        <%= label_tag(:state, "publish") %>
      </label>
      <label class="radio">
        <%= radio_button("post", "state", FALSE) %>
        <%= label_tag(:state, "draft") %>
      </label>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th>Category</th>
      <th>Status</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.post_category.name %></td>
        <td><%
          if post.state == TRUE
          %>
            <span class="label label-success">Publish</span>
          <%  else  %>
            <span class="label label-warning">Draft</span>
          <% end   %></td>
        <td><%=l post.created_at %></td>
        <td align="center">
          <%= link_to edit_post_path(post), :class => 'btn btn-small' do %>
            <i class="icon-pencil"></i> <%= t("helpers.links.edit") %>
          <% end   %>
          <%= link_to post_path(post),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-small btn-danger' do %>
            <i class="icon-trash"></i> <%= t("helpers.links.destroy") %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_post_path, :class => 'btn btn-primary' do %>
  <i class="icon-plus"></i> <%= t("helpers.links.new") %>
<% end  %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= strip_tags @post.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= if @post.picture.blank?
      puts ''
    else
      @post.picture
    end%></dd>

  <dt><strong>Tag</strong></dt>
  <dd><% @post.tags.any? %>
    <% @post.tags.each do |tag| %>
      <%= link_to tag.name, tagged_url(:tag => tag.name) %>
    <% end %></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
    posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    post_path(@post),
    :method => 'delete',
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
    :class => 'btn btn-danger' %>
</div>