config/routes.rb
LatihanBlog::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_for :authentications, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :post_categories

  get "comment/index"

  get "comment/create"

  get "search" => "frontpage#search"

  mount Ckeditor::Engine => '/ckeditor'

  get "frontpage/index"

  get "about_me" => 'frontpage#about_me', :as => :about_me
  get "contact_me" => 'frontpage#contact_me', :as => :contact_me
  post "send_contact" => "frontpage#send_contact", :as => :send_contact
  get "portfolios" => "frontpage#portfolios", :as => :portfolios
  get "frontpage/:id/detail_post" => "frontpage#detail_post", :as => :detail_post
  post "frontpage/add_new_comment" => "frontpage#add_new_comment"
  get "frontpage/:id/category_post" => "frontpage#category_post", :as => :category_post

  resources :posts do
    resources :comments
  end

  match 'tagged' => 'posts#tagged', :as => 'tagged'
  match 'tagged_front' => 'frontpage#tagged', :as => 'taggedfront'

  root :to => 'frontpage#index'

end

app/views/layouts/_myfacebook.html.erb
<!-- Facebook Badge START --><a href="https://www.facebook.com/naklieur" target="_TOP" title="Mada Aryakusumah"><img src="https://badge.facebook.com/badge/1644263451.1247.1028442878.png" style="border: 0px;" /></a><!-- Facebook Badge END -->

app/views/layouts/_twitterbutton.html.erb
<a href="https://twitter.com/madha14" class="twitter-follow-button" data-show-count="false" data-size="large" data-dnt="true">Follow @madha14</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Mada's Blog", root_path, :class => "brand" %>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= nav_link("Portfolios", portfolios_path) %></li>
              <li><%= nav_link("Contact Me", contact_me_path) %></li>
              <% if user_signed_in? %>
                <li><%= link_to "My Post", posts_path %></li>

              <%  end %>
            </ul>
            <%= form_tag('/search', :method => "get", :class=> "navbar-search pull-left" ) do %>
              <%= search_field_tag 'word', params[:word], :placeholder => "search", :class=> "search-query span2" %>
            <% end %>

          </div>
          <% if user_signed_in? %>
            <div class="nav-collapse pull-right">
              <ul class="nav">
                <li><%= link_to "My account", edit_user_registration_path %></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </div>
          <%  end %>

          <% unless user_signed_in? %>
            <div class="nav-collapse pull-right">
              <ul class="nav">
                <li class="dropdown" id="menu1">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
                    Login
                    <b class="caret"></b>
                  </a>
                  <div class="dropdown-menu pull-right">
                    <%= form_for("user", :url => user_session_path) do |f| %>
                      <fieldset class='textbox' style="padding:10px">
                        <%= f.email_field :email, :placeholder => "email" %>
                        <%=  f.password_field :password, :placeholder => "password" %>
                        <input class="btn btn-primary" name="commit" type="submit" value="Log In" /> <%= link_to "Sign up", new_user_registration_path %>

                      </fieldset>
                    <% end %>
                  </div>
                </li>
              </ul>
            </div>
          <% end %>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span9">
          <% if alert  %>
            <div class="alert">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= alert %>
            </div>
          <% end %>
          <% if notice  %>
            <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= notice %>
            </div>
          <% end %>

          <%= yield %>
        </div>
        <div class="span3">
          <%= yield :sidebar %>
          <h2>About Me</h2>
          <p>My name is Mada Aryakusumah.</p>
          <p><%= link_to "Detail »", about_me_path, :class => "btn"   %></p>
        </div>
        <% cache do   %>
          <div class="span3">
            <%= render :partial => 'layouts/myfacebook' %>
          </div>

          <div class="span3" style="padding-top: 10px">
            <%= render :partial => 'layouts/twitterbutton' %>
          </div>
        <% end   %>

        <div class="span3" style="padding-top: 10px">
          <h2>Category</h2>
          <ul>
            <% @post_categories.each do |category| %>
              <li><%= link_to category.name, category_post_path(category) %></li>
            <% end  %>
          </ul>
        </div>

      </div>
    </div>
  </body>
</html>

app/views/layouts/sidebar.html.erb
<% content_for :sidebar do %>
<h2>About Us</h2>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
<% end  %>